# Generated by Django 3.2.3 on 2021-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashare', '0002_auto_20210530_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='amount',
            field=models.CharField(max_length=100, verbose_name='股数'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=24, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=100, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='company',
            name='value',
            field=models.CharField(max_length=100, verbose_name='市值'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='t_date',
            field=models.DateField(verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='t_type',
            field=models.IntegerField(choices=[(0, '15日新高'), (1, '30日新高'), (2, '60日新高'), (3, '180日新高'), (4, '收缩走势')], verbose_name='策略类型'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.CharField(max_length=200, verbose_name='交易数量'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='close',
            field=models.IntegerField(verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='high',
            field=models.IntegerField(verbose_name='高点'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='low',
            field=models.IntegerField(verbose_name='低点'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open',
            field=models.IntegerField(verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='t_date',
            field=models.DateField(verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='value',
            field=models.CharField(max_length=200, verbose_name='交易金额'),
        ),
    ]
