# Generated by Django 3.2.3 on 2021-07-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashare', '0003_auto_20210530_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='板块名称')),
                ('t_date', models.DateField(verbose_name='统计日期')),
                ('t_type', models.IntegerField(choices=[(0, '15日新高'), (1, '30日新高'), (2, '60日新高'), (3, '120日新高'), (4, '收缩走势')], verbose_name='策略类型')),
            ],
            options={
                'verbose_name_plural': '板块信息',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': '公司'},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': '策略筛选'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name_plural': '每日交易数据'},
        ),
        migrations.AlterField(
            model_name='strategy',
            name='t_type',
            field=models.IntegerField(choices=[(0, '15日新高'), (1, '30日新高'), (2, '60日新高'), (3, '120日新高'), (4, '收缩走势')], verbose_name='策略类型'),
        ),
    ]
