# Generated by Django 3.2.3 on 2021-07-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashare', '0004_auto_20210713_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='number',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
