# Generated by Django 3.2.3 on 2021-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashare', '0005_industry_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.CharField(default='', max_length=1024, verbose_name='公司主页'),
            preserve_default=False,
        ),
    ]
